## Load Data

In [1]:
# Import Package
import numpy as np
import pandas as pd

In [2]:
# Load dataset
df = pd.read_csv('dataset.csv')

In [3]:
df

sepal.length  sepal.width  petal.length  petal.width    variety  label
0             5.1          3.5           1.4          0.2     Setosa      0
1             4.9          3.0           1.4          0.2     Setosa      0
2             4.7          3.2           1.3          0.2     Setosa      0
3             4.6          3.1           1.5          0.2     Setosa      0
4             5.0          3.6           1.4          0.2     Setosa      0
..            ...          ...           ...          ...        ...    ...
145           6.7          3.0           5.2          2.3  Virginica      2
146           6.3          2.5           5.0          1.9  Virginica      2
147           6.5          3.0           5.2          2.0  Virginica      2
148           6.2          3.4           5.4          2.3  Virginica      2
149           5.9          3.0           5.1          1.8  Virginica      2

[150 rows x 6 columns]

In [5]:
# Cek tipedata df
df.dtypes

sepal.length    float64
sepal.width     float64
petal.length    float64
petal.width     float64
variety          object
label             int64
dtype: object

In [6]:
# Akses kolom df
df.columns

Index(['sepal.length', 'sepal.width', 'petal.length', 'petal.width', 'variety',
       'label'],
      dtype='object')

In [7]:
# Akses kolom sepal.length
df['sepal.length'].values

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [9]:
# Akses hanya nilai semua kolom
feature = df[['sepal.length', 'sepal.width', 'petal.length', 'petal.width']].values

In [10]:
# Akses label
label = df['label'].values

In [11]:
# Ubah ke numpy array
x = np.array(feature)
y = np.array(label)

In [12]:
x.shape

(150, 4)

In [13]:
y.shape

(150,)

## Training Model

In [14]:
from sklearn.preprocessing import StandardScaler

$$\frac{x-mean}{std}$$

In [25]:
# Mencari rata-rata per kolom / per atribut
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [15]:
atribut_mean = x.mean(axis=0)

In [16]:
atribut_std = x.std(axis=0)

## Normalisasi

In [17]:
x_norm = StandardScaler().fit_transform(x)

In [26]:
x_norm.shape

(150, 4)

In [27]:
x_norm

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

## Training
### Train test split

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
x_train, x_test, y_train, y_test = train_test_split(x_norm, y, test_size=0.25, stratify=y, random_state=12)

In [20]:
x_train.shape

(112, 4)

In [21]:
x_test.shape

(38, 4)

## Training neural network

In [24]:
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

In [29]:
# Membuat blueprint model
model = Sequential()

# Tentukan layer per model
model.add(Dense(64, input_dim=4, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(3, activation='softmax'))

# Tentukan loss, algoritma belajar, dan jenis evaluasi
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [30]:
# Isi data ke neural network dan train
model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=100)

Epoch 1/100
4/4 [==============================] - 0s 61ms/step - loss: 1.1008 - accuracy: 0.3036 - val_loss: 1.0220 - val_accuracy: 0.4474
Epoch 2/100
4/4 [==============================] - 0s 4ms/step - loss: 0.9958 - accuracy: 0.5357 - val_loss: 0.9374 - val_accuracy: 0.5789
Epoch 3/100
4/4 [==============================] - 0s 5ms/step - loss: 0.9100 - accuracy: 0.6786 - val_loss: 0.8686 - val_accuracy: 0.7632
Epoch 4/100
4/4 [==============================] - 0s 4ms/step - loss: 0.8377 - accuracy: 0.8036 - val_loss: 0.8117 - val_accuracy: 0.7632
Epoch 5/100
4/4 [==============================] - 0s 5ms/step - loss: 0.7762 - accuracy: 0.8482 - val_loss: 0.7638 - val_accuracy: 0.7895
Epoch 6/100
4/4 [==============================] - 0s 9ms/step - loss: 0.7242 - accuracy: 0.8482 - val_loss: 0.7205 - val_accuracy: 0.7632
Epoch 7/100
4/4 [==============================] - 0s 4ms/step - loss: 0.6795 - accuracy: 0.8571 - val_loss: 0.6821 - val_accuracy: 0.7632
Epoch 8/100
4/4 [=========

4/4 [==============================] - 0s 4ms/step - loss: 0.0681 - accuracy: 0.9821 - val_loss: 0.2191 - val_accuracy: 0.8947
Epoch 60/100
4/4 [==============================] - 0s 5ms/step - loss: 0.0663 - accuracy: 0.9821 - val_loss: 0.2162 - val_accuracy: 0.8947
Epoch 61/100
4/4 [==============================] - 0s 4ms/step - loss: 0.0645 - accuracy: 0.9911 - val_loss: 0.2132 - val_accuracy: 0.8947
Epoch 62/100
4/4 [==============================] - 0s 5ms/step - loss: 0.0634 - accuracy: 0.9911 - val_loss: 0.2114 - val_accuracy: 0.8947
Epoch 63/100
4/4 [==============================] - 0s 4ms/step - loss: 0.0615 - accuracy: 0.9911 - val_loss: 0.2063 - val_accuracy: 0.9211
Epoch 64/100
4/4 [==============================] - 0s 4ms/step - loss: 0.0596 - accuracy: 0.9911 - val_loss: 0.2036 - val_accuracy: 0.9211
Epoch 65/100
4/4 [==============================] - 0s 4ms/step - loss: 0.0584 - accuracy: 0.9911 - val_loss: 0.1994 - val_accuracy: 0.9211
Epoch 66/100
4/4 [===============

### Save model

In [31]:
model.save('model.h5')

### Load model

In [32]:
from tensorflow.keras.models import load_model

In [33]:
model = load_model('model.h5')

----------------

### Predictions

#### Prepare data

In [38]:
# Menggunakan data dari df
df.iloc[100, :]

sepal.length          6.3
sepal.width           3.3
petal.length            6
petal.width           2.5
variety         Virginica
label                   2
Name: 100, dtype: object

In [39]:
new_data = [[6.3, 3.3, 6, 2.5]]

In [40]:
x_pred = np.array(new_data)

In [41]:
x_pred

array([[6.3, 3.3, 6. , 2.5]])

### Normalisasi

In [42]:
atribut_mean

array([5.84333333, 3.05733333, 3.758     , 1.19933333])

In [43]:
atribut_std

array([0.82530129, 0.43441097, 1.75940407, 0.75969263])

In [44]:
df.columns

Index(['sepal.length', 'sepal.width', 'petal.length', 'petal.width', 'variety',
       'label'],
      dtype='object')

In [45]:
df.iloc[100, :]

sepal.length          6.3
sepal.width           3.3
petal.length            6
petal.width           2.5
variety         Virginica
label                   2
Name: 100, dtype: object

$$\frac{x-mean}{std}$$

In [47]:
sepalLength = (6.3 - atribut_mean[0]) / atribut_std[0]
sepalWidth = (3.3 - atribut_mean[1]) / atribut_std[1]
petalLength = (6 - atribut_mean[2]) / atribut_std[2]
petalWidth = (2.5 - atribut_mean[3]) / atribut_std[3]

In [48]:
xPred = np.array([[sepalLength, sepalWidth, petalLength, petalWidth]])

### Prediction

In [50]:
hasil = model.predict(xPred)

In [51]:
hasil

array([[6.7841011e-06, 5.7797355e-04, 9.9941528e-01]], dtype=float32)

In [52]:
np.argmax(hasil, axis=1)

array([2], dtype=int64)